### ISSUE TITLE
adding entry to webpack.config.js

### ISSUE THREAD

**Issue by chrismcleod** [asprouse/serverless-webpack-plugin#22]
@Sanjo this pull request https://github.com/asprouse/serverless-webpack-plugin/pull/21

added support for loading modules before the handler.  However, when I do as the docs suggest I get this error:

``` shell
Serverless:   my-function: Path must be a string. Received [ 'babel-polyfill' ]

...


/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:61
        fn = function () { throw arg; };
                           ^
ServerlessError: Function Deployment Failed
    at new ServerlessError (/usr/local/lib/node_modules/serverless/lib/Error.js:17:11)
    at FunctionDeploy.<anonymous> (/usr/local/lib/node_modules/serverless/lib/actions/FunctionDeploy.js:126:19)
    at next (/usr/local/lib/node_modules/serverless/node_modules/rimraf/rimraf.js:74:7)
    at FSReqWrap.CB [as oncomplete] (/usr/local/lib/node_modules/serverless/node_modules/rimraf/rimraf.js:110:9)
From previous event:
    at FunctionDeploy.functionDeploy (/usr/local/lib/node_modules/serverless/lib/actions/FunctionDeploy.js:105:10)
From previous event:
    at /usr/local/lib/node_modules/serverless/lib/Serverless.js:211:25
    at Array.reduce (native)
    at Serverless._execute (/usr/local/lib/node_modules/serverless/lib/Serverless.js:210:26)
    at Object.actions.(anonymous function) [as functionDeplo
```

this is my webpack.config.js:

``` javascript
var webpack = require("webpack");

module.exports = {
  target: "node",
  entry: ["babel-polyfill"],
  externals: [
    "aws-sdk"
  ],
  resolve: {
    extensions: ["", ".js"]
  },
  devtool: "source-map",
  plugins: [
    new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/),
    new webpack.optimize.DedupePlugin(),
    new webpack.optimize.OccurenceOrderPlugin(),
    new webpack.optimize.UglifyJsPlugin({
      compress: {
        unused: true,
        dead_code: true,
        warnings: false,
        drop_debugger: true
      }
    })
  ],
  module: {
    loaders: [
      {
        test: /\.jsx?$/,
        loader: "babel",
        exclude: /node_modules/,
        query: {
          presets: ["es2015", "node6", "stage-0"]
        }
      }
    ]
  }
};
```

**Comment by asprouse** [comment]
I am having trouble reproducing this can you provide more details about your environment? What does your s-function.json have in the handler field?

**Comment by chrismcleod** [comment]
Im not sure what was going on, it eventually started working after i messed with a lot of stuff.  Maybe I had another webpack.config.js somewhere that was interfering
